# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c8c43bf9e360cb6e1f97b1c6978dcd8479f5f1c437b7f2d1b38d40bc8d708fc2013ec4cbe1074d9f1de15ed4f29b63c3cac50d0ee7fb3ad2075b4e69653a107a

test:
  secret_key_base: d3f4440a7db3dffdd36bf2830cc94cafba18c126cadbb432e1e441a104098762f252756c098726f89a18bfd7e500f4ad98fabd1160f29a3f51c88f231e3bd50c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
